In [1]:
import pandas as pd

In [2]:
# Series - 1D data 
# DataFrames - 2D data - rows and columns inthe form of table 

df= pd.DataFrame([12,34,55,43,100])
df

     0
0   12
1   34
2   55
3   43
4  100

In [ ]:
df= pd.DataFrame([[12,10,11,100],[10,54,33,22]])

In [6]:
df

    0   1   2    3
0  12  10  11  100
1  10  54  33   22

In [56]:
# dictionary -
df= pd.DataFrame({'Name':['Aryan','Vasu','Jasbir','Prachi','Sham','Raaju'],'Rollno':[12,34,33,21,10,34], 'class':['Bca','Mba','bba','bba','btech','btech']})
df

     Name  Rollno  class
0   Aryan      12    Bca
1    Vasu      34    Mba
2  Jasbir      33    bba
3  Prachi      21    bba
4    Sham      10  btech
5   Raaju      34  btech

In [57]:
df.head()

     Name  Rollno  class
0   Aryan      12    Bca
1    Vasu      34    Mba
2  Jasbir      33    bba
3  Prachi      21    bba
4    Sham      10  btech

In [58]:
df.tail()

     Name  Rollno  class
1    Vasu      34    Mba
2  Jasbir      33    bba
3  Prachi      21    bba
4    Sham      10  btech
5   Raaju      34  btech

In [59]:
df.shape

(6, 3)

In [60]:
# access [], .
# df['Name']
# df['class']
df[['Name','class']][:3]

     Name class
0   Aryan   Bca
1    Vasu   Mba
2  Jasbir   bba

In [61]:
df['Name'][:3] # column, row

0     Aryan
1      Vasu
2    Jasbir
Name: Name, dtype: object

In [62]:
# df[3]['Name'] error

In [63]:
df[1:]

     Name  Rollno  class
1    Vasu      34    Mba
2  Jasbir      33    bba
3  Prachi      21    bba
4    Sham      10  btech
5   Raaju      34  btech

In [64]:
# loc, iloc

In [65]:
df.loc[:3,:]  # rows, column

     Name  Rollno class
0   Aryan      12   Bca
1    Vasu      34   Mba
2  Jasbir      33   bba
3  Prachi      21   bba

In [66]:
df.iloc[:3,:]  # rows, column

     Name  Rollno class
0   Aryan      12   Bca
1    Vasu      34   Mba
2  Jasbir      33   bba

In [67]:
df.loc[:,'Name']

0     Aryan
1      Vasu
2    Jasbir
3    Prachi
4      Sham
5     Raaju
Name: Name, dtype: object

In [68]:
df.loc[:2,['Name','class']]

     Name class
0   Aryan   Bca
1    Vasu   Mba
2  Jasbir   bba

In [69]:
df.iloc[:,:2]

     Name  Rollno
0   Aryan      12
1    Vasu      34
2  Jasbir      33
3  Prachi      21
4    Sham      10
5   Raaju      34

In [70]:
df.loc[2,['Name','class']]

Name     Jasbir
class       bba
Name: 2, dtype: object

In [71]:
# update 
df.loc[2,'class']='Mtech'

In [72]:
df

     Name  Rollno  class
0   Aryan      12    Bca
1    Vasu      34    Mba
2  Jasbir      33  Mtech
3  Prachi      21    bba
4    Sham      10  btech
5   Raaju      34  btech

In [73]:
df.loc[5,'Rollno']=100

In [74]:
df

     Name  Rollno  class
0   Aryan      12    Bca
1    Vasu      34    Mba
2  Jasbir      33  Mtech
3  Prachi      21    bba
4    Sham      10  btech
5   Raaju     100  btech

In [75]:
df.loc[:,'Rollno']=[10,12,14,16,19,32]

In [76]:
df

     Name  Rollno  class
0   Aryan      10    Bca
1    Vasu      12    Mba
2  Jasbir      14  Mtech
3  Prachi      16    bba
4    Sham      19  btech
5   Raaju      32  btech

In [77]:
# add column

In [78]:
df.loc[:,'Total Marks']=50

In [79]:
df

     Name  Rollno  class  Total Marks
0   Aryan      10    Bca           50
1    Vasu      12    Mba           50
2  Jasbir      14  Mtech           50
3  Prachi      16    bba           50
4    Sham      19  btech           50
5   Raaju      32  btech           50

In [80]:
df.insert(loc=2,column='marks',value=[45,43,46,44,39,30])

In [81]:
df

     Name  Rollno  marks  class  Total Marks
0   Aryan      10     45    Bca           50
1    Vasu      12     43    Mba           50
2  Jasbir      14     46  Mtech           50
3  Prachi      16     44    bba           50
4    Sham      19     39  btech           50
5   Raaju      32     30  btech           50

In [82]:
df.loc[:,'Percentage']= (df.loc[:,'marks']/df.loc[:,'Total Marks'])*100

In [83]:
df

     Name  Rollno  marks  class  Total Marks  Percentage
0   Aryan      10     45    Bca           50        90.0
1    Vasu      12     43    Mba           50        86.0
2  Jasbir      14     46  Mtech           50        92.0
3  Prachi      16     44    bba           50        88.0
4    Sham      19     39  btech           50        78.0
5   Raaju      32     30  btech           50        60.0

In [ ]:
df.loc[8,:]=['Nikhal',12,47,'bca',50,94]

In [85]:
df

     Name  Rollno  marks  class  Total Marks  Percentage
0   Aryan    10.0   45.0    Bca         50.0        90.0
1    Vasu    12.0   43.0    Mba         50.0        86.0
2  Jasbir    14.0   46.0  Mtech         50.0        92.0
3  Prachi    16.0   44.0    bba         50.0        88.0
4    Sham    19.0   39.0  btech         50.0        78.0
5   Raaju    32.0   30.0  btech         50.0        60.0
8  Nikhal    12.0   47.0    bca         50.0        94.0

In [86]:
# conditions

In [88]:
df[df.loc[:,'class']=='btech']

    Name  Rollno  marks  class  Total Marks  Percentage
4   Sham    19.0   39.0  btech         50.0        78.0
5  Raaju    32.0   30.0  btech         50.0        60.0

In [ ]:
# df.loc[:,'class']

0      Bca
1      Mba
2    Mtech
3      bba
4    btech
5    btech
8      bca
Name: class, dtype: object

In [99]:
df[(df.loc[:,'class']=='btech') | (df.loc[:,'Percentage']>80)]

     Name  Rollno  marks  class  Total Marks  Percentage
0   Aryan    10.0   45.0    Bca         50.0        90.0
1    Vasu    12.0   43.0    Mba         50.0        86.0
2  Jasbir    14.0   46.0  Mtech         50.0        92.0
3  Prachi    16.0   44.0    bba         50.0        88.0
4    Sham    19.0   39.0  btech         50.0        78.0
5   Raaju    32.0   30.0  btech         50.0        60.0
8  Nikhal    12.0   47.0    bca         50.0        94.0