In [1]:
import pandas as pd
df= pd.DataFrame({'Name':['Aryan','Vasu','Jasbir','Prachi','Sham','Raaju'],'Rollno':[12,34,33,21,10,34], 'class':['Bca','Mba','bba','bba','btech','btech']})
df

     Name  Rollno  class
0   Aryan      12    Bca
1    Vasu      34    Mba
2  Jasbir      33    bba
3  Prachi      21    bba
4    Sham      10  btech
5   Raaju      34  btech

In [3]:
df.insert(loc=2,column='marks',value=[45,43,46,44,39,30])
df

     Name  Rollno  marks  class
0   Aryan      12     45    Bca
1    Vasu      34     43    Mba
2  Jasbir      33     46    bba
3  Prachi      21     44    bba
4    Sham      10     39  btech
5   Raaju      34     30  btech

In [4]:
# sort_values 
df.sort_values(by='marks')

     Name  Rollno  marks  class
5   Raaju      34     30  btech
4    Sham      10     39  btech
1    Vasu      34     43    Mba
3  Prachi      21     44    bba
0   Aryan      12     45    Bca
2  Jasbir      33     46    bba

In [6]:
df.sort_values(by='marks', ascending=False,ignore_index=True )

     Name  Rollno  marks  class
0  Jasbir      33     46    bba
1   Aryan      12     45    Bca
2  Prachi      21     44    bba
3    Vasu      34     43    Mba
4    Sham      10     39  btech
5   Raaju      34     30  btech

In [8]:
df.info() # dataframe information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Rollno  6 non-null      int64
 2   marks   6 non-null      int64
 3   class   6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [9]:
df.columns

Index(['Name', 'Rollno', 'marks', 'class'], dtype='object')

In [10]:
# iterrows
df

     Name  Rollno  marks  class
0   Aryan      12     45    Bca
1    Vasu      34     43    Mba
2  Jasbir      33     46    bba
3  Prachi      21     44    bba
4    Sham      10     39  btech
5   Raaju      34     30  btech

In [12]:
for i in df.iterrows():
    print(i)

(0, Name      Aryan
Rollno       12
marks        45
class       Bca
Name: 0, dtype: object)
(1, Name      Vasu
Rollno      34
marks       43
class      Mba
Name: 1, dtype: object)
(2, Name      Jasbir
Rollno        33
marks         46
class        bba
Name: 2, dtype: object)
(3, Name      Prachi
Rollno        21
marks         44
class        bba
Name: 3, dtype: object)
(4, Name       Sham
Rollno       10
marks        39
class     btech
Name: 4, dtype: object)
(5, Name      Raaju
Rollno       34
marks        30
class     btech
Name: 5, dtype: object)

In [14]:
df.describe()

          Rollno      marks
count   6.000000   6.000000
mean   24.000000  41.166667
std    11.224972   5.980524
min    10.000000  30.000000
25%    14.250000  40.000000
50%    27.000000  43.500000
75%    33.750000  44.750000
max    34.000000  46.000000

In [15]:
data= pd.DataFrame({'marks':[12,14,18,19,20]})
data

   marks
0     12
1     14
2     18
3     19
4     20

In [17]:
data.describe()

           marks
count   5.000000
mean   16.600000
std     3.435113
min    12.000000
25%    14.000000
50%    18.000000
75%    19.000000
max    20.000000

In [19]:
data= pd.DataFrame({'marks':[12,14,18,19,20,22]})
data.describe()

           marks
count   6.000000
mean   17.500000
std     3.781534
min    12.000000
25%    15.000000
50%    18.500000
75%    19.750000
max    22.000000

In [26]:
# list - [] 
# tuple - ()
# dictionary - {}
# sets - {} 

# a=(12,)
# print(type(a))

# s={}
# s=set()
# print(type(s))

# list comprehension

In [29]:
# Write a recursive function to compute the sum of digits of a number until a single digit remains.
# Example: 9875 → 9+8+7+5=29 → 2+9=11 → 1+1=2

def funcRe(a):
    sum=0
    for i in a:
        i=int(i)
        sum+=i
    if len(str(sum))==1:
        print(sum)
    else:
        funcRe(str(sum))


funcRe("99913234")

4