In [2]:
# find null values, csv files read, excel files read
import pandas as pd
import numpy as np # pip install numpy
df= pd.DataFrame({'Name':['Aryan','Vasu','Jasbir',np.nan,'Prachi','Sham','Raaju'],'Rollno':[12,34,33,21,np.nan,10,34], 'class':['Bca','Mba','bba',np.nan,'bba',np.nan,'btech']})
df

     Name  Rollno  class
0   Aryan    12.0    Bca
1    Vasu    34.0    Mba
2  Jasbir    33.0    bba
3     NaN    21.0    NaN
4  Prachi     NaN    bba
5    Sham    10.0    NaN
6   Raaju    34.0  btech

In [3]:
# Data Preprocessing 
# data cleaning 
df.isnull()

    Name  Rollno  class
0  False   False  False
1  False   False  False
2  False   False  False
3   True   False   True
4  False    True  False
5  False   False   True
6  False   False  False

In [ ]:
# df.to_excel('data.xlsx')

In [5]:
df.isnull().any()

Name      True
Rollno    True
class     True
dtype: bool

In [6]:
df.isnull().sum()

Name      1
Rollno    1
class     2
dtype: int64

In [7]:
df.isna().sum()

Name      1
Rollno    1
class     2
dtype: int64

In [9]:
df

     Name  Rollno  class
0   Aryan    12.0    Bca
1    Vasu    34.0    Mba
2  Jasbir    33.0    bba
3     NaN    21.0    NaN
4  Prachi     NaN    bba
5    Sham    10.0    NaN
6   Raaju    34.0  btech

In [8]:
# Fill or delete nan values 
df.dropna()

     Name  Rollno  class
0   Aryan    12.0    Bca
1    Vasu    34.0    Mba
2  Jasbir    33.0    bba
6   Raaju    34.0  btech

In [ ]:
df.dropna(axis=1)  # axis-1 for column and 0 for row

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [11]:
# df.dropna(inplace=True)

In [12]:
df

     Name  Rollno  class
0   Aryan    12.0    Bca
1    Vasu    34.0    Mba
2  Jasbir    33.0    bba
3     NaN    21.0    NaN
4  Prachi     NaN    bba
5    Sham    10.0    NaN
6   Raaju    34.0  btech

In [14]:
df.rename(columns={'Rollno':'Marks'},inplace=True)

In [15]:
df

     Name  Marks  class
0   Aryan   12.0    Bca
1    Vasu   34.0    Mba
2  Jasbir   33.0    bba
3     NaN   21.0    NaN
4  Prachi    NaN    bba
5    Sham   10.0    NaN
6   Raaju   34.0  btech

In [16]:
df.Marks.mean()

24.0

In [17]:
df.fillna(34)

     Name  Marks  class
0   Aryan   12.0    Bca
1    Vasu   34.0    Mba
2  Jasbir   33.0    bba
3      34   21.0     34
4  Prachi   34.0    bba
5    Sham   10.0     34
6   Raaju   34.0  btech

In [20]:
df.Marks.fillna(df.Marks.mean(), inplace=True)

In [21]:
df

     Name  Marks  class
0   Aryan   12.0    Bca
1    Vasu   34.0    Mba
2  Jasbir   33.0    bba
3     NaN   21.0    NaN
4  Prachi   24.0    bba
5    Sham   10.0    NaN
6   Raaju   34.0  btech

In [26]:
df.loc[:,'class'].mode()

0    bba
Name: class, dtype: object

In [55]:
cars= pd.read_csv("pre-owned cars.csv")

In [56]:
cars.head(2)

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX

In [57]:
# pd.read_csv('E:/PyGenAI9/GenAI0900/DS/AI_Impact_on_Jobs_2030.csv')

In [58]:
a=pd.read_excel('data.xlsx')
# pip install openpyxl

In [59]:
a

   Unnamed: 0    Name  Rollno  class
0           0   Aryan    12.0    Bca
1           1    Vasu    34.0    Mba
2           2  Jasbir    33.0    bba
3           3     NaN    21.0    NaN
4           4  Prachi     NaN    bba
5           5    Sham    10.0    NaN
6           6   Raaju    34.0  btech

In [60]:
a=a.drop('Unnamed: 0', axis=1)
a

     Name  Rollno  class
0   Aryan    12.0    Bca
1    Vasu    34.0    Mba
2  Jasbir    33.0    bba
3     NaN    21.0    NaN
4  Prachi     NaN    bba
5    Sham    10.0    NaN
6   Raaju    34.0  btech

In [61]:
cars.head(2)

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX

In [62]:
cars.columns

Index(['brand', 'model', 'transmission', 'make_year', 'reg_year', 'fuel_type',
       'engine_capacity(CC)', 'km_driven', 'ownership', 'price',
       'overall_cost', 'has_insurance', 'spare_key', 'reg_number', 'title'],
      dtype='object')

In [63]:
cars.shape

(2806, 15)

In [64]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806 entries, 0 to 2805
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                2805 non-null   object
 1   model                2805 non-null   object
 2   transmission         2805 non-null   object
 3   make_year            2805 non-null   float64
 4   reg_year             720 non-null    object
 5   fuel_type            2805 non-null   object
 6   engine_capacity(CC)  2688 non-null   float64
 7   km_driven            2805 non-null   float64
 8   ownership            2805 non-null   object
 9   price                2806 non-null   int64
 10  overall_cost         2805 non-null   float64
 11  has_insurance        2805 non-null   object
 12  spare_key            2805 non-null   object
 13  reg_number           2805 non-null   object
 14  title                2805 non-null   object
dtypes: float64(4), int64(1), object(10)
memory usage: 329.0+ KB

In [65]:
cars.isnull().sum()

brand                     1
model                     1
transmission              1
make_year                 1
reg_year               2086
fuel_type                 1
engine_capacity(CC)     118
km_driven                 1
ownership                 1
price                     0
overall_cost              1
has_insurance             1
spare_key                 1
reg_number                1
title                     1
dtype: int64

In [66]:
cars.drop('reg_year', axis=1, inplace=True)

In [67]:
cars

,brand,model,transmission,make_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT
2802,Honda,Jazz 1.2L I-VTEC V,Manual,2015.0,Petrol,1199.0,38706.0,2nd owner,412000,8057.0,True,Yes,MH01,2015 Honda Jazz 1.2L I-VTEC V
2803,Hyundai,Elite i20 MAGNA 1.2,Manual,2016.0,Petrol,1197.0,31405.0,1st owner,496000,9704.0,True,Yes,MH03,2016 Hyundai Elite i20 MAGNA 1.2
2804,Maruti,Baleno DELTA PETROL 1.2,Manual,2017.0,Petrol,1197.0,47676.0,1st owner,509000,9959.0,True,Yes,MH04,2017 Maruti Baleno DELTA PETROL 1.2
2805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1883558000,NaN,NaN,NaN,NaN,NaN

In [68]:
cars.dropna(inplace=True)

In [69]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2688 entries, 0 to 2804
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                2688 non-null   object
 1   model                2688 non-null   object
 2   transmission         2688 non-null   object
 3   make_year            2688 non-null   float64
 4   fuel_type            2688 non-null   object
 5   engine_capacity(CC)  2688 non-null   float64
 6   km_driven            2688 non-null   float64
 7   ownership            2688 non-null   object
 8   price                2688 non-null   int64
 9   overall_cost         2688 non-null   float64
 10  has_insurance        2688 non-null   object
 11  spare_key            2688 non-null   object
 12  reg_number           2688 non-null   object
 13  title                2688 non-null   object
dtypes: float64(4), int64(1), object(9)
memory usage: 315.0+ KB

In [70]:
cars.isnull().sum()

brand                  0
model                  0
transmission           0
make_year              0
fuel_type              0
engine_capacity(CC)    0
km_driven              0
ownership              0
price                  0
overall_cost           0
has_insurance          0
spare_key              0
reg_number             0
title                  0
dtype: int64