In [6]:
import pandas as pd
df= pd.DataFrame({'Name':['Aryan','Vasu','Jasbir','Prachi','Sham','Raaju'],'Rollno':[12,34,33,21,10,34], 'class':['Bca','Mba','bba','bba','btech','btech']})
df

     Name  Rollno  class
0   Aryan      12    Bca
1    Vasu      34    Mba
2  Jasbir      33    bba
3  Prachi      21    bba
4    Sham      10  btech
5   Raaju      34  btech

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Rollno  6 non-null      int64
 2   class   6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [14]:
df.loc[:,'class']=df.loc[:,'class'].str.upper()

In [15]:
df

     Name  Rollno  class
0   Aryan      12    BCA
1    Vasu      34    MBA
2  Jasbir      33    BBA
3  Prachi      21    BBA
4    Sham      10  BTECH
5   Raaju      34  BTECH

In [20]:
df.Rollno= df.Rollno.astype('str')

In [24]:
df.Rollno.dtype

dtype('O')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Rollno  6 non-null      object
 2   class   6 non-null      object
dtypes: object(3)
memory usage: 276.0+ bytes

In [23]:
# map, apply_map 
df.applymap(lambda x: x+"hi")

C:\Users\hp\AppData\Local\Temp\ipykernel_17972\4056939485.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x+"hi")

       Name Rollno    class
0   Aryanhi   12hi    BCAhi
1    Vasuhi   34hi    MBAhi
2  Jasbirhi   33hi    BBAhi
3  Prachihi   21hi    BBAhi
4    Shamhi   10hi  BTECHhi
5   Raajuhi   34hi  BTECHhi

In [25]:
t= pd.read_csv('Titanic-Dataset.csv')
t

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
t.loc[:,'Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [27]:
t.loc[:,'Sex'].map({'male':0,'female':1})

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

In [28]:
t.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
df

     Name Rollno  class
0   Aryan     12    BCA
1    Vasu     34    MBA
2  Jasbir     33    BBA
3  Prachi     21    BBA
4    Sham     10  BTECH
5   Raaju     34  BTECH

In [31]:
df.rename(columns={'class':'Degree'}, inplace=True) # old:new

In [32]:
df

     Name Rollno Degree
0   Aryan     12    BCA
1    Vasu     34    MBA
2  Jasbir     33    BBA
3  Prachi     21    BBA
4    Sham     10  BTECH
5   Raaju     34  BTECH